namespace TomRR.Cli.Toolkit.Commands;

public static class CommandEmitter
{
    public static void Emit(
        SourceProductionContext context,
        ImmutableArray<CommandToGenerate> commands)
    {
        foreach (var command in commands)
        {
            context.AddSource($"{command.ClassName}.Command.g.cs", SourceText.From(SourceCode(command), Encoding.UTF8));
        }
    }

    private static void Generate(SourceProductionContext context, ImmutableArray<CommandToGenerate> commands)
    {
        foreach (var command in commands)
        {
            context.AddSource(
                $"{command.ClassName}.Command.g.cs",
                SourceText.From(SourceCode(command), Encoding.UTF8));
        }
    }
    private static string SourceCode(CommandToGenerate command)
    {
        var bodyBuilder = new StringBuilder();

        AppendName(command.CommandName, bodyBuilder);
        AppendDescription(command.Description, bodyBuilder);
        AppendShortNames(command.ShortNames?.ToList() ?? [], bodyBuilder);
        
        var classBody = bodyBuilder.ToString().TrimEnd();
        
        return $@"//<auto-generated/>
#nullable enable

namespace {command.Namespace};

public sealed partial class {command.ClassName}
{{
{classBody}
}}";
    }
    
    private static void AppendName(string commandName, StringBuilder bodyBuilder)
    {
        if (!string.IsNullOrWhiteSpace(commandName))
        {
            var normalizeCommandName = CommandNameParser.NormalizeCommandName(commandName);
            bodyBuilder.AppendLine($@"    private string CommandName => ""{normalizeCommandName}"";");
        }
    }
    private static void AppendDescription(string? description, StringBuilder bodyBuilder)
    {
        if (!string.IsNullOrWhiteSpace(description))
        {
            bodyBuilder.AppendLine($@"    private string Description => ""{description}"";");
        }
    }
    private static void AppendShortNames(List<string>? commandShortNames, StringBuilder bodyBuilder)
    {
        if (commandShortNames is not null && commandShortNames.Any())
        {
            var quotedNames = commandShortNames.Select(s => $"\"{s}\"");
            var arrayInitializer = string.Join(", ", quotedNames);
            bodyBuilder.AppendLine($@"    private string[] ShortNamesArray => new string[] {{ {arrayInitializer} }};");
        }
    }
}