using System.Collections.Immutable;

namespace TomRR.Cli.Toolkit.Commands;

public static class CommandEmitter
{
    public static void Emit(IncrementalGeneratorInitializationContext context, IncrementalValueProvider<ImmutableArray<CommandClassModel>> commandClasses)
    {
        context.RegisterSourceOutput(commandClasses,
            static (spc, arr) => Generate(spc, arr));
    }

    private static void Generate(SourceProductionContext context, ImmutableArray<CommandClassModel> commands)
    {
        foreach (var command in commands)
        {
            context.AddSource(
                $"{command.ClassName}.Command.g.cs",
                SourceText.From(SourceCode(command), Encoding.UTF8));
        }
    }
    private static string SourceCode(CommandClassModel command)
    {
        var bodyBuilder = new StringBuilder();

        AppendName(command.CommandName, bodyBuilder);
        AppendDescription(command.CommandDescription, bodyBuilder);
        AppendShortNames(command.CommandShortNames, bodyBuilder);
        
        var classBody = bodyBuilder.ToString().TrimEnd();
        
        return $@"//<auto-generated/>
#nullable enable

namespace {command.Namespace};

public sealed partial class {command.ClassName}
{{
{classBody}
}}";
    }
    
    private static void AppendName(string commandName, StringBuilder bodyBuilder)
    {
        if (!string.IsNullOrWhiteSpace(commandName))
        {
            bodyBuilder.AppendLine($@"    private string CommandName => ""{commandName}"";");
        }
    }
    private static void AppendDescription(string? description, StringBuilder bodyBuilder)
    {
        if (!string.IsNullOrWhiteSpace(description))
        {
            bodyBuilder.AppendLine($@"    private string Description => ""{description}"";");
        }
    }
    private static void AppendShortNames(string[]? commandShortNames, StringBuilder bodyBuilder)
    {
        if (commandShortNames is not null && commandShortNames.Any())
        {
            var quotedNames = commandShortNames.Select(s => $"\"{s}\"");
            var arrayInitializer = string.Join(", ", quotedNames);
            bodyBuilder.AppendLine($@"    private string[] ShortNamesArray => new string[] {{ {arrayInitializer} }};");
        }
    }
}