namespace TomRR.Cli.Toolkit.Attributes;

internal static partial class AttributesEmitter
{
    private const string ArgumentAttributeName = "ArgumentAttribute";
    private const string OptionAttributeName = "OptionAttribute";
    private const string CommandAttributeName = "CommandAttribute";
    public static void Emit(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(ctx =>
        {
            ctx.AddSource(
                $"{ArgumentAttributeName}.g.cs",
                SourceText.From(SourceCode(ArgumentAttributeName, ArgumentCodeBody, "AttributeTargets.Property"), Encoding.UTF8));
            ctx.AddSource(
                $"{CommandAttributeName}.g.cs",
                SourceText.From(SourceCode(CommandAttributeName, CommandCodeBody, "AttributeTargets.Class"), Encoding.UTF8));
            ctx.AddSource(
                $"{OptionAttributeName}.g.cs",
                SourceText.From(SourceCode(OptionAttributeName, OptionCodeBody, "AttributeTargets.Property"), Encoding.UTF8));
        });
    }

    private static string SourceCode(string attributeName, string codeBody, string attributeTarget) => $@"//<auto-generated/>
#nullable enable

namespace {Constance.NamespaceBase}.Attributes;

[global::System.AttributeUsage(global::System.{attributeTarget}, AllowMultiple = false)]
public sealed partial class {attributeName} : global::System.Attribute
{{{codeBody}}}";
    
    private const string ArgumentCodeBody = $@"
    /// <summary>
    /// The name of the option property this argument belongs to (if any).
    /// Use nameof(OptionProperty) to keep it type-safe.
    /// </summary>
    public string OfOption {{ get; }}
    /// <summary>
    /// Position of this argument relative to the command or its corresponding option.
    /// </summary>
    public int Position {{ get; }}
    public ArgumentAttribute(string ofOption, int position = 0)
    {{
        OfOption = ofOption;
        Position = position;
    }}
";
    
    private const string CommandCodeBody = $@"
    public string? Name {{ get; }}
    public string?[] ShortNames {{ get; }}
    public string? Description {{ get; }}
    
    public CommandAttribute(string? name = null, string? description = null, params string?[] shortNames)
    {{
        Name = name;
        ShortNames = shortNames;
        Description = description;
    }}
";
    private const string OptionCodeBody = $@"
    public string LongName {{ get; }}
    public string? ShortName {{ get; }}
    public bool HasValue {{ get; }}
    public string? Description {{ get; }}

    public OptionAttribute(string longName, string? shortName = null, bool hasValue = true, string? description = null)
    {{
        LongName = longName;
        ShortName = shortName;
        HasValue = hasValue;
        Description = description;
    }}
";
}