namespace TomRR.Cli.Toolkit.DependencyInjections;

public static class DependencyInjectionEmitter
{
    
    private const string CommandName = "Commands";
    private const string CliAppBuilderName = "CliAppBuilderExtensions";
    private static string GetFileName(string name) => $"{name}.DependencyInjection.g.cs";
    private static string GetClassName(string name) => $"{name}_DependencyInjection";
    public static void Emit(
        IncrementalGeneratorInitializationContext context, 
        IncrementalValueProvider<ImmutableArray<(string Namespace, string ClassName, string CommandName, string[]? CommandShortNames, string? CommandDescription)>> commandClasses)
    {
        context.RegisterSourceOutput(commandClasses,
            static (spc, arr) => GenerateDependencyInection(spc, arr));
    }

    private static void GenerateDependencyInection(
        SourceProductionContext context,
        ImmutableArray<(string Namespace, string ClassName, string CommandName, string[]? CommandShortNames, string? CommandDescription)> commands)
    {
        context.AddSource(
            GetFileName(CommandName),
            SourceText.From(CommandsInjectionSourceCode(commands, GetClassName(CommandName)), Encoding.UTF8));
        context.AddSource(
            GetFileName(CliAppBuilderName),
            SourceText.From(CliAppBuilderInjectionSourceCode(GetClassName(CliAppBuilderName)), Encoding.UTF8));
    }
    
    private static string CommandsInjectionSourceCode(IEnumerable<(string Namespace, string ClassName, string CommandName, string[]? CommandShortNames, string? CommandDescription)> commands, string className) => $@"//<auto-generated/>
#nullable enable

namespace {Constance.NamespaceBase};

public static partial class {className}
{{
    public static global::{Constance.NamespaceBaseAbstractions}.ICliAppBuilder AddCommands(this global::{Constance.NamespaceBaseAbstractions}.ICliAppBuilder builder)
    {{
        {AddCommands(commands)}
        return builder;
    }}
}}
";

    private static string AddCommands(
        IEnumerable<(string Namespace, string ClassName, string CommandName, string[]? CommandShortNames, string?
            CommandDescription)> commands)
    {
        var sb = new StringBuilder();
        var indent = "        "; // 8 spaces, for method body alignment
        int index = 0;

        foreach (var command in commands)
        {
            // prepare arguments
            var args = new List<string> { $"\"{command.CommandName}\"" };
            if (command.CommandShortNames != null && command.CommandShortNames.Length > 0)
                args.AddRange(command.CommandShortNames.Select(s => $"\"{s}\""));
            var argsString = string.Join(", ", args);

            // choose indentation: no indent for first, indent for others
            var currentIndent = index == 0 ? "" : indent;

            // optional description comment
            if (!string.IsNullOrWhiteSpace(command.CommandDescription))
                sb.AppendLine($"{currentIndent}// Description: {command.CommandDescription}");

            // builder line
            sb.AppendLine(
                $"{currentIndent}builder.AddCommand<global::{command.Namespace}.{command.ClassName}>({argsString});");

            index++;
        }

        return sb.ToString();
    }

    private static string CliAppBuilderInjectionSourceCode(string className) => $@"//<auto-generated/>
#nullable enable

namespace {Constance.NamespaceBase};

public static partial class {className}
{{            
    public static global::{Constance.NamespaceBaseAbstractions}.ICliAppBuilder AddToolkitDependencies(
        this global::{Constance.NamespaceBaseAbstractions}.ICliAppBuilder builder)
    {{
        builder.AddCommandDispatcher();
        builder.AddCommandBinderRegistry();

        return builder;
    }}

    public static global::{Constance.NamespaceBaseAbstractions}.ICliAppBuilder AddCommandDispatcher(
        this global::{Constance.NamespaceBaseAbstractions}.ICliAppBuilder builder)
    {{
        return builder.AddDependencies(services =>
        {{
            global::Microsoft.Extensions.DependencyInjection.ServiceCollectionServiceExtensions
                .AddSingleton
                <
                    global::{Constance.NamespaceBaseAbstractions}.ICommandDispatcher,
                    global::{Constance.NamespaceBase}.CommandDispatcher
                >(services);
        }});
    }}

    public static global::{Constance.NamespaceBaseAbstractions}.ICliAppBuilder AddCommandBinderRegistry(
        this global::{Constance.NamespaceBaseAbstractions}.ICliAppBuilder builder)
    {{
        return builder.AddDependencies(services =>
        {{
            global::Microsoft.Extensions.DependencyInjection.ServiceCollectionServiceExtensions
                .AddSingleton
                <
                    global::{Constance.NamespaceBaseAbstractions}.ICommandBinderRegistry,
                    global::{Constance.NamespaceBaseSourceGenerator}.CommandBinders.CommandBinderRegistry
                >(services);
        }});
    }}
}}
";
}

