namespace TomRR.Cli.Toolkit.DependencyInjections;

public static class DependencyInjectionEmitter
{
    
    private const string CommandName = "Commands";
    private const string CliAppBuilderName = "CliAppBuilderExtensions";
    private static string GetFileName(string name) => $"{name}.DependencyInjection.g.cs";
    private static string GetClassName(string name) => $"{name}_DependencyInjection";
    public static void Emit(
        SourceProductionContext context,
        ImmutableArray<CommandToGenerate> commands)
    {

        var sortCommands = commands.SortByName();
        context.AddSource(
            GetFileName(CommandName),
            SourceText.From(CommandsInjectionSourceCode(sortCommands, GetClassName(CommandName)), Encoding.UTF8));
        
        context.AddSource(
            GetFileName(CliAppBuilderName),
            SourceText.From(CliAppBuilderInjectionSourceCode(GetClassName(CliAppBuilderName)), Encoding.UTF8));
    }

    private static void GenerateDependencyInjection(
        SourceProductionContext context,
        ImmutableArray<CommandToGenerate> commands)
    {
        context.AddSource(
            GetFileName(CommandName),
            SourceText.From(CommandsInjectionSourceCode(commands, GetClassName(CommandName)), Encoding.UTF8));
        context.AddSource(
            GetFileName(CliAppBuilderName),
            SourceText.From(CliAppBuilderInjectionSourceCode(GetClassName(CliAppBuilderName)), Encoding.UTF8));
    }
    
    private static string CommandsInjectionSourceCode(IEnumerable<CommandToGenerate> commands, string className) => $@"//<auto-generated/>
#nullable enable

namespace {Constance.NamespaceBase};

public static partial class {className}
{{
    /// <summary>
    /// Registers all discovered commands that are decorated with the [Command] attribute.
    /// </summary>
    public static global::{Constance.NamespaceBaseAbstractions}.ICliAppBuilder AddCommands(this global::{Constance.NamespaceBaseAbstractions}.ICliAppBuilder builder)
    {{
{AddCommands(commands)}

        return builder;
    }}
}}
";

        private static string AddCommands(
            IEnumerable<CommandToGenerate> commands)
        {
            var sb = new StringBuilder();
            // This is the correct indentation (8 spaces) needed inside the C# method body.
            const string indent = "        "; 

            foreach (var command in commands)
            {
                // ADDED: Insert a blank line before the next command, unless it's the first one.
                if (sb.Length > 0)
                {
                    sb.AppendLine();
                }
                
                // prepare arguments
                var normalizeCommandName = CommandNameParser.NormalizeCommandName(command.CommandName);
                var args = new List<string> { $"\"{normalizeCommandName}\"" };
                if (command.ShortNames != null && command.ShortNames.Any())
                {
                    args.AddRange(command.ShortNames.Select(s => $"\"{s}\""));
                }   
                var argsString = string.Join(", ", args);

                // optional description comment - ALWAYS use full indent
                if (!string.IsNullOrWhiteSpace(command.Description))
                {
                    sb.AppendLine($"{indent}// Description: {command.Description}");
                }
                
                // builder line - ALWAYS use full indent
                sb.Append($"{indent}builder.AddCommand<global::{command.Namespace}.{command.ClassName}>({argsString});");
            }

            return sb.ToString();
        }

    private static string CliAppBuilderInjectionSourceCode(string className) => $@"//<auto-generated/>
#nullable enable

namespace {Constance.NamespaceBase};

public static partial class {className}
{{            
    public static global::{Constance.NamespaceBaseAbstractions}.ICliAppBuilder AddToolkitDependencies(
        this global::{Constance.NamespaceBaseAbstractions}.ICliAppBuilder builder)
    {{
        builder.AddCommandDispatcher();
        builder.AddCommandBinderRegistry();

        return builder;
    }}

    public static global::TomRR.Cli.Toolkit.Abstractions.ICliAppBuilder AddCommandDispatcher(
        this global::TomRR.Cli.Toolkit.Abstractions.ICliAppBuilder builder)
    {{
        return builder.AddDependencies(services =>
    {{
        // 1. Register the concrete class (using the full static method call)
        global::Microsoft.Extensions.DependencyInjection.ServiceCollectionServiceExtensions
            .AddSingleton<global::TomRR.Cli.Toolkit.CommandDispatcher>(services);

        // 2. Register the interface to forward to the concrete class (also using the full static method call)
        global::Microsoft.Extensions.DependencyInjection.ServiceCollectionServiceExtensions
            .AddSingleton<global::TomRR.Cli.Toolkit.Abstractions.ICommandDispatcher>(
                services, // The 'this IServiceCollection' argument
                sp =>     // The factory function
                    global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions
                        .GetRequiredService<global::TomRR.Cli.Toolkit.CommandDispatcher>(sp)
            );
    }});
    }}

    public static global::{Constance.NamespaceBaseAbstractions}.ICliAppBuilder AddCommandBinderRegistry(
        this global::{Constance.NamespaceBaseAbstractions}.ICliAppBuilder builder)
    {{
        return builder.AddDependencies(services =>
        {{
            global::Microsoft.Extensions.DependencyInjection.ServiceCollectionServiceExtensions
                .AddSingleton
                <
                    global::{Constance.NamespaceBaseAbstractions}.ICommandBinderRegistry,
                    global::{Constance.NamespaceBaseSourceGenerator}.CommandBinders.CommandBinderRegistry
                >(services);
        }});
    }}
}}
";
}
