using System.Text;
using Microsoft.CodeAnalysis.Text;

namespace TomRR.Cli.Toolkit.Generators.AttributeGenerators;

public static class ArgumentAttributeGenerator
{
    private const string AttributeName = "ArgumentAttribute";
    public static void Generate(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(ctx 
            => ctx.AddSource(
                $"{AttributeName}.g.cs",
                SourceText.From(SourceCode, Encoding.UTF8)));
    }
    private const string SourceCode = $@"//<auto-generated/>
#nullable enable
using System;

namespace {Constance.NamespaceBase}.Attributes;

[AttributeUsage(AttributeTargets.Property, AllowMultiple = false)]
public sealed class {AttributeName} : Attribute
{{
    /// <summary>
    /// The name of the option property this argument belongs to (if any).
    /// Use nameof(OptionProperty) to keep it type-safe.
    /// </summary>
    public string OfOption {{ get; }}
    /// <summary>
    /// Position of this argument relative to the command or its corresponding option.
    /// </summary>
    public int Position {{ get; }}
    public ArgumentAttribute(string ofOption, int position = 0)
    {{
        OfOption = ofOption;
        Position = position;
    }}
}}";
}