using System.Text;
using Microsoft.CodeAnalysis.Text;

namespace TomRR.Cli.Toolkit.Generators.AttributeGenerators;

public static class CommandAttributeGenerator
{
    private const string AttributeName = "CommandAttribute";
    public static void Generate(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(ctx 
            => ctx.AddSource(
                $"{AttributeName}.g.cs",
                SourceText.From(SourceCode, Encoding.UTF8)));
    }
    
    private const string SourceCode = $@"//<auto-generated/>
#nullable enable
using System;

namespace {Constance.NamespaceBase}.Attributes;

[AttributeUsage(AttributeTargets.Class, Inherited = false)]
public sealed class {AttributeName} : Attribute
{{
    public string? Name {{ get; }}
    public string?[] ShortNames {{ get; }}
    public string? Description {{ get; }}
    
    public CommandAttribute(string? name = null, string? description = null, params string?[] shortNames)
    {{
        Name = name;
        ShortNames = shortNames;
        Description = description;
    }}
}}";
}