using System.Text;
using Microsoft.CodeAnalysis.Text;

namespace TomRR.Cli.Toolkit.Generators.AttributeGenerators;

public static class OptionAttributeGenerator
{
    private const string AttributeName = "OptionAttribute";

    public static void Generate(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(ctx 
            => ctx.AddSource(
                $"{AttributeName}.g.cs",
                SourceText.From(SourceCode, Encoding.UTF8)));
    }
    
    private const string SourceCode = $@"//<auto-generated/>
#nullable enable
using System;

namespace {Constance.NamespaceBase}.Attributes;

[AttributeUsage(AttributeTargets.Property, AllowMultiple = false)]
public sealed class {AttributeName} : Attribute
{{
    public string LongName {{ get; }}
    public string? ShortName {{ get; }}
    public bool HasValue {{ get; }}
    public string? Description {{ get; }}

    public OptionAttribute(string longName, string? shortName = null, bool hasValue = true, string? description = null)
    {{
        LongName = longName;
        ShortName = shortName;
        HasValue = hasValue;
        Description = description;
    }}
}}";
}