namespace TomRR.Cli.Toolkit.Generators.CoreGeneratorCodes;

public static class CliApp
{
    public const string SourceCode = $@"//<auto-generated/>
#nullable enable
using System.Threading.Tasks;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;

namespace {Constance.NamespaceBase};

public class CliApp
{{
    private readonly IHost _host;

    internal CliApp(IHost host) => _host = host;

    public async Task RunAsync(string[] args)
    {{
        var dispatcher = _host.Services.GetRequiredService<CommandDispatcher>();
        await dispatcher.DispatchAsync(args);
    }}
}}";
}