using System.Text;

namespace TomRR.Cli.Toolkit.Generators.CoreGeneratorCodes;

public static class CommandDependencyInjection
{
    public static string SourceCode(IEnumerable<(string Namespace, string ClassName, string CommandName, string[]? CommandShortNames, string? CommandDescription)> commands) => $@"//<auto-generated/>
#nullable enable
namespace {Constance.NamespaceBase};

public static partial class DependencyInjection
{{
    public static CliAppBuilder AddCommands(this CliAppBuilder builder)
    {{
        {AddCommands(commands)}
        return builder;
    }}
}}
";

    private static string AddCommands(
        IEnumerable<(string Namespace, string ClassName, string CommandName, string[]? CommandShortNames, string?
            CommandDescription)> commands)
    {
        var sb = new StringBuilder();
        var indent = "        "; // 8 spaces, for method body alignment
        int index = 0;

        foreach (var command in commands)
        {
            // prepare arguments
            var args = new List<string> { $"\"{command.CommandName}\"" };
            if (command.CommandShortNames != null && command.CommandShortNames.Length > 0)
                args.AddRange(command.CommandShortNames.Select(s => $"\"{s}\""));
            var argsString = string.Join(", ", args);

            // choose indentation: no indent for first, indent for others
            var currentIndent = index == 0 ? "" : indent;

            // optional description comment
            if (!string.IsNullOrWhiteSpace(command.CommandDescription))
                sb.AppendLine($"{currentIndent}// Description: {command.CommandDescription}");

            // builder line
            sb.AppendLine(
                $"{currentIndent}builder.AddCommand<global::{command.Namespace}.{command.ClassName}>({argsString});");

            index++;
        }

        return sb.ToString();
    }
}