namespace TomRR.Cli.Toolkit.Generators.CoreGeneratorCodes;

public static class CommandBinderRegistryCode
{
    public const string SourceCode = $@"//<auto-generated/>
#nullable enable
using Microsoft.Extensions.DependencyInjection;
namespace {Constance.NamespaceBase};


public static partial class DependencyInjection
{{
    public static global::{Constance.NamespaceBase}.CliAppBuilder AddCommandBinderRegistry(
        this global::{Constance.NamespaceBase}.CliAppBuilder builder)
    {{
        return builder.AddDependencies(services =>
        {{
            services.AddSingleton<global::{Constance.NamespaceBase}.ICommandBinderRegistry, global::{Constance.NamespaceBase}.CommandBinders.CommandBinderRegistry>();
        }});
    }}
}}
";
}

