namespace TomRR.Cli.Toolkit.Generators.CommandBinders.CommandBinder;

public static class CommandBinderCode
{
    public static string SourceCode() => $@"//<auto-generated/>
#nullable enable
using System;
using System.Threading.Tasks;
using Cli.Toolkit.SourceGenerators;

namespace {Constance.NamespaceBase}.CommandBinders;

public static class AddCommand_Binder
{{
    public static void Bind(AddCommand cmd, string[] args)
    {{
        for (var i = 0; i < args.Length; i++)
        {{
            var token = args[i];

            switch (token)
            {{
                case ""--interactive"":
                case ""-i"":
                    cmd.Interactive = true;
                    break;
                
                case ""--select"":
                case ""-s"":
                    cmd.Select = true;
                    if (TryGetNext(args, ref i, out var repo))
                    {{
                        cmd.SelectedRepositoryName = repo;
                    }}                    
                    break;

                // --- Unknown tokens ---
                default:
                    // Optional: log unknown flag for debugging
                    // Console.WriteLine($""Unknown option: {{token}}"");
                    break;
            }}
        }}
    }}
";
    public static string TryGetNextCode = $@"

private static bool TryGetNext(string[] args, ref int index, out string value)
{{
    value = string.Empty;
    if (index + 1 >= args.Length)
    {{
        return false;
    }}
        
    var next = args[index + 1];
    if (next.StartsWith(""-""))
    {{
        return false;
    }}
        
    value = next;
    index++; // advance since we consumed it
    return true;
}}
";
}