using System.Text;
using Microsoft.CodeAnalysis.Text;

namespace TomRR.Cli.Toolkit.Generators.Interfaces;

public static class InterfaceGenerator
{
    public static void Generate(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(ctx 
            => ctx.AddSource(
                $"ICommand.g.cs",
                SourceText.From(SourceCodeICommand, Encoding.UTF8)));
        context.RegisterPostInitializationOutput(ctx 
            => ctx.AddSource(
                $"ICommandBinderRegistry.g.cs",
                SourceText.From(SourceCodeICommandBinderRegistry, Encoding.UTF8)));
    }
    
    private const string SourceCodeICommand = $@"//<auto-generated/>
#nullable enable
namespace {Constance.NamespaceBase};

public interface ICommand
{{
    public global::System.Threading.Tasks.Task RunAsync();
}}";
    private const string SourceCodeICommandBinderRegistry = $@"//<auto-generated/>
#nullable enable
namespace {Constance.NamespaceBase};

public interface ICommandBinderRegistry
{{
    public global::System.Threading.Tasks.Task BindAndRun(ICommand cmd, string[] args);
}}";
}