using System.Text;

namespace TomRR.Cli.Toolkit.Generators.CommandBinders.CommandBinderRegistryGenerator;

public static class CommandBinderRegistryCode
{
    public static string SourceCode(IEnumerable<(string Namespace, string ClassName, string CommandName, string[]? CommandShortNames, string? CommandDescription)> commands) => $@"//<auto-generated/>
#nullable enable
using System;
using System.Threading.Tasks;

namespace {Constance.NamespaceBase}.CommandBinders;

public class CommandBinderRegistry  : ICommandBinderRegistry
{{
    public async global::System.Threading.Tasks.Task BindAndRun(ICommand cmd, string[] args)
    {{
        switch (cmd)
        {{
            {BindCommands(commands)}
            default:
                throw new InvalidOperationException(
                    $""No binder generated for command type {{cmd.GetType().FullName}}"");
        }}
    }}
}}
";
    
    private static string BindCommands(
        IEnumerable<(string Namespace, string ClassName, string CommandName, string[]? CommandShortNames, string?
            CommandDescription)> commands)
    {
        var sb = new StringBuilder();
        var indent = "            "; 
        int index = 0;
        int lastIndex = commands.Count() - 1;
        foreach (var command in commands)
        {
            var currentIndent = index == 0 ? "" : indent;

            sb.AppendLine($"{currentIndent}case global::{command.Namespace}.{command.ClassName} command:");
            sb.AppendLine($"    {indent}global::{Constance.NamespaceBase}.CommandBinders.{command.ClassName}_Binder.Bind(command, args);");
            sb.AppendLine($"    {indent}await command.RunAsync();");
            sb.AppendLine($"    {indent}break;");
            if (index != lastIndex)
            {
                sb.AppendLine();

            }
            index++;
        }

        return sb.ToString();
    }
}
