namespace TomRR.Cli.Toolkit.CommandBinders;

public static class CommandBinderRegistryEmitter
{
    public static void Emit(
        SourceProductionContext context,
        ImmutableArray<(string Namespace, string ClassName, string CommandName, string[]? CommandShortNames, string? CommandDescription)> commands)
    {
        context.AddSource(
            $"_CommandBinderRegistry.g.cs",
            SourceText.From(SourceCode(commands), Encoding.UTF8));
    }
    
    private static string SourceCode(IEnumerable<(string Namespace, string ClassName, string CommandName, string[]? CommandShortNames, string? CommandDescription)> commands) => $@"//<auto-generated/>
#nullable enable

namespace {Constance.NamespaceBaseSourceGenerator}.CommandBinders;

public sealed partial class CommandBinderRegistry : global::{Constance.NamespaceBaseAbstractions}.ICommandBinderRegistry
{{
    public async global::System.Threading.Tasks.Task BindAndRun(global::{Constance.NamespaceBaseAbstractions}.ICommand cmd, string[] args)
    {{
        switch (cmd)
        {{
            {BindCommands(commands)}
            default:
                throw new global::System.InvalidOperationException(
                    $""No binder generated for command type {{cmd.GetType().FullName}}"");
        }}
    }}
}}
";
    
    private static string BindCommands(
        IEnumerable<(string Namespace, string ClassName, string CommandName, string[]? CommandShortNames, string?
            CommandDescription)> commands)
    {
        var sb = new StringBuilder();
        var indent = "            "; 
        int index = 0;
        int lastIndex = commands.Count() - 1;
        foreach (var command in commands)
        {
            var currentIndent = index == 0 ? "" : indent;

            sb.AppendLine($"{currentIndent}case global::{command.Namespace}.{command.ClassName} command:");
            sb.AppendLine($"    {indent}global::{Constance.NamespaceBaseSourceGenerator}.CommandBinders.{command.ClassName}_Binder.Bind(command, args);");
            sb.AppendLine($"    {indent}await command.RunAsync();");
            sb.AppendLine($"    {indent}break;");
            if (index != lastIndex)
            {
                sb.AppendLine();

            }
            index++;
        }

        return sb.ToString();
    }
    
}