namespace TomRR.Cli.Toolkit.CommandBinders;

public static class CommandBinderEmitter
{

    public static void Emit(
        SourceProductionContext context,
        ImmutableArray<CommandToGenerate> commands)
    {

        foreach (var command in commands)
        {
            var builder = GenerateBinder(command);
            context.AddSource($"{command.ClassName}_Binder.g.cs", SourceText.From(builder.ToString(), Encoding.UTF8));
        }
    }
    private static StringBuilder GenerateBinder(CommandToGenerate command)
    {
        var builder = new StringBuilder();

        builder.AppendLine("//<auto-generated/>");
        builder.AppendLine("#nullable enable");
        builder.AppendLine();
        // Use the command's namespace, or a hardcoded one if you prefer
        builder.AppendLine($"namespace {Constance.NamespaceBaseSourceGenerator}.CommandBinders;"); 
        builder.AppendLine();
        builder.AppendLine($"public static class {command.ClassName}_Binder");
        builder.AppendLine("{");
        builder.AppendLine($"    public static void Bind(global::{command.Namespace}.{command.ClassName} cmd, string[] args)");
        builder.AppendLine("    {");
        builder.AppendLine("        for (var i = 0; i < args.Length; i++)");
        builder.AppendLine("        {");
        builder.AppendLine("            var token = args[i];");
        builder.AppendLine("            switch (token)");
        builder.AppendLine("            {");

        // var sortOptions = Sorting.SortOptions(command.Options);

        // Generate cases for each option
        foreach (var option in command.Options)
        {
            builder.AppendLine($"                case \"{option.LongName}\":");
            if (!string.IsNullOrEmpty(option.ShortName))
            {
                builder.AppendLine($"                case \"{option.ShortName}\":");
            }
            
            // Set the option's flag (e.g., cmd.Interactive = true;)
            builder.AppendLine($"                    cmd.{option.PropertyName} = true;");

            // Generate argument parsing
            if (option.Arguments.Count > 0)
            {
                builder.AppendLine($"                    // --- Parse {option.Arguments.Count} arg(s) for {option.LongName} ---");
                foreach (var arg in option.Arguments) // Already sorted
                {
                    builder.AppendLine($"                    if (TryGetNext(args, ref i, out var arg{arg.Position}_{arg.PropertyName}))");
                    builder.AppendLine("                    {");
                    // TODO: Add type conversion if arg.PropertyType isn't string
                    builder.AppendLine($"                        cmd.{arg.PropertyName} = arg{arg.Position}_{arg.PropertyName};");
                    builder.AppendLine("                    }");
                    // builder.AppendLine("                    else");
                    // builder.AppendLine("                    {");
                    // builder.AppendLine($"                        // Optional: Handle missing argument for {arg.PropertyName}");
                    // builder.AppendLine("                    }");
                }
            }
            
            builder.AppendLine("                    break;");
            builder.AppendLine(); 
        }

        builder.AppendLine("                default:");
        builder.AppendLine("                    // Optional: log unknown flag");
        builder.AppendLine("                    break;");
        builder.AppendLine("            }");
        builder.AppendLine("        }");
        builder.AppendLine("    }");
        builder.AppendLine();
        
        // Add the helper method
        builder.AppendLine($"{TryGetNextCode}");
        
        builder.AppendLine("}"); // End class
        
        return builder;
    }
    
    public static string TryGetNextCode = $@"    private static bool TryGetNext(string[] args, ref int index, out string value)
    {{
        value = string.Empty;
        if (index + 1 >= args.Length)
        {{
            return false;
        }}
        
        var next = args[index + 1];
        if (next.StartsWith(""-""))
        {{
            return false;
        }}
        
        value = next;
        index++; // advance since we consumed it
        return true;
    }}";
}